theme: jekyll-theme-slate
title: Saul Ramirez's Page
description: Welcome to my personal page ! I'll be using this Github Site as my digital resume, I'll keep it up to date with latest worth sharing news related to my professinal career.
