theme: jekyll-theme-slate
title: Welcome to Saul Ramirez's Page
description: Thanks for visiting me! I'm using this Github Site as my digital resume, I'll keep it up to date with latest worth sharing news related to my professinal career.
